#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi

if [[ "$1" != "setup" ]]; then
  echo "Syntax: 'carbonio-docs-editor setup' to automatically configure the service"
  exit 1;
fi

# Decrypt the bootstrap token, asking the password to the sys admin
# --setup check for SETUP_CONSUL_TOKEN env. variable and uses it
# to avoid re-asking for the password
echo -n "Insert the cluster credential password: "
export CONSUL_HTTP_TOKEN=$(service-discover bootstrap-token --setup)
EXIT_CODE="$?"
echo ""
if [[ "${EXIT_CODE}" != "0" ]]; then
  echo "Cannot access to bootstrap token"
  exit 1;
fi
# Limit secret visibility as much as possible
export -n SETUP_CONSUL_TOKEN

# Generate service-router, service-resolver config and update carbonio-docs-editor.hcl
serviceId=$(uuidgen)
python3 /usr/lib/carbonio-docs-routes-generator.py \
  -s carbonio-docs-editor \
  -p service_id \
  -i "$serviceId" \
  -d /etc/carbonio/docs-editor/service-discover/

POLICY_NAME='carbonio-docs-editor-policy'
POLICY_DESCRIPTION='Carbonio Docs Editor service policy for service and sidecar proxy'

# create or update policy for the specific service (this will be shared across cluster)
consul acl policy create -name "${POLICY_NAME}" -description "${POLICY_DESCRIPTION}" -rules @/etc/carbonio/docs-editor/service-discover/policies.json >/dev/null 2>&1
if [[ "$?" != "0" ]]; then
    consul acl policy update -no-merge -name "${POLICY_NAME}" -description "${POLICY_DESCRIPTION}" -rules @/etc/carbonio/docs-editor/service-discover/policies.json
    if [[ "$?" != "0" ]]; then
      echo "Setup failed: Cannot update policy for ${POLICY_NAME}"
      exit 1
    fi
fi

# Declare the service as http
consul config write /etc/carbonio/docs-editor/service-discover/service-protocol.json

# Allow other services to contact this service
consul config write /etc/carbonio/docs-editor/service-discover/intentions.json

if [[ ! -f "/etc/carbonio/docs-editor/service-discover/token" ]]; then
    # Create the token
    consul acl token create -format json -policy-name "${POLICY_NAME}" -description "Token for
    carobonio-docs-editor/$(hostname -A)" |
      jq -r '.SecretID' > /etc/carbonio/docs-editor/service-discover/token;
    chown carbonio-docs-editor:carbonio-docs-editor /etc/carbonio/docs-editor/service-discover/token
    chmod 0600 /etc/carbonio/docs-editor/service-discover/token

    # To pass the token to consul-template we need to inject it to a env. variable
    # since it doesn't accept a file as an argument
    mkdir -p /etc/systemd/system/carbonio-docs-editor.service.d/
    cat >/etc/systemd/system/carbonio-docs-editor.service.d/override.conf <<EOF
[Service]
Environment="CONSUL_HTTP_TOKEN=$(cat /etc/carbonio/docs-editor/service-discover/token)"
EOF
    chmod 0600 /etc/systemd/system/carbonio-docs-editor.service.d/override.conf
    systemctl daemon-reload
fi

# These three commands MUST be executed in this order:
# 1. reload consul in order to register the service via carbonio-docs-editor.hcl
# 2. write the service-resolver config in order to associate the Subsets ids for
#    each docs-editor instance. It works only if the service is already registered
# 3. write the service-router config in order to define the docs-editor routing
#    It works only if the Subsets ids are applied to each instance.
consul reload
consul config write /etc/carbonio/docs-editor/service-discover/service-resolver.json
consul config write /etc/carbonio/docs-editor/service-discover/service-router.json


# Limit token visibility as much as possible
export -n CONSUL_HTTP_TOKEN

systemctl restart carbonio-docs-editor.service
systemctl restart carbonio-docs-editor-sidecar.service
